NEW: Extension points for FilesystemPublisher.
silverstripe/silverstripe-staticpublishqueue pull request #137
Opened 2022-05-12 23:15 UTC by mfendeksilverstripe

# NEW: Extension points for FilesystemPublisher.

* Extension points added to `generatePageResponse()` to allow better extensibility

2022-05-12 23:28 UTC, dhensby commented
The idea behind the publisher classes is that developers can easily implement their own and add their own logic easily. There shouldn't really be a need for extension hooks with the current implementation.

What is the scenario where this is needed?

2022-05-12 23:40 UTC, mfendeksilverstripe commented
@dhensby My team found useful to have the ability to inject some custom behaviour via these extension points. For example we have in-memory cache which needs to be flushed after each call of `generatePageResponse()`. It's not something that warrants the implementation of a new file system publisher as we're not altering any core behaviour but instead a simple extension can accomodate this requirement.

Also, we found useful to reset some core states such as controller stack something like this:

```php
try {
    $controllers = [];

    // pop all current application's controllers to simulate cold boot
    while (Controller::has_curr()) {
        $controller = Controller::curr();
        $controllers[]= $controller;
        $controller->popCurrent();
    }

    return parent::generatePageResponse($url);
} finally {
    // flush all in-memory cached data

    foreach (array_reverse($controllers) as $controller) {
        // reapply previous controllers
        $controller->pushCurrent();
    }
}
```

2023-12-18 21:18 UTC, GuySartorelli requested changes
Your use case seems sensible to me. Please retarget this PR to the `6` branch and remove the unrelated changes.

2023-12-18 21:18 UTC, GuySartorelli commented on src/Publisher/FilesystemPublisher.php
> +            return [];
Why is this change here? It seems out of scope for adding extension points. If there is a valid reason to change what is returned here, please create a separate PR for this purpose which can be reviewed and merged on its own merits.
```suggestion
```

2023-12-18 21:18 UTC, GuySartorelli commented on src/Publisher/FilesystemPublisher.php
> +            return [];
```suggestion
```

2023-12-22 00:28 UTC, mfendeksilverstripe commented
I've pushed up changes as per your request @GuySartorelli , please review.

2023-12-22 00:30 UTC, GuySartorelli commented
You swapped the target branch _after_ resetting commits, which means the new CI isn't able to run. Can you please force push so that the CI runs correctly?

2023-12-22 00:33 UTC, mfendeksilverstripe commented
Done @GuySartorelli

2023-12-22 00:34 UTC, GuySartorelli approved these changes
Changes look good to me, will merge when CI goes green.

2023-12-22 00:36 UTC, merged