BUG: Typecast URLsToProcess to an array
silverstripe/silverstripe-staticpublishqueue pull request #147
Opened 2022-10-05 22:52 UTC by textagroup

If URLsToProcess is null then a error will be thrown when trying to create a Delete cache job because array_keys expects an array.

[Emergency] Uncaught TypeError: array_keys(): Argument #1 ($array) must be of type array, null given
POST /admin/queuedjobs/Symbiote-QueuedJobs-DataObjects-QueuedJobDescriptor/EditForm
Line 107 in /var/www/stats/vendor/silverstripe/staticpublishqueue/src/Job.ph

2022-10-06 23:38 UTC, GuySartorelli requested changes
Please also include a test where a job is processed with no URLs to process.

2022-10-06 23:38 UTC, GuySartorelli commented on src/Job.php
> +            array_keys((array)$this->URLstoProcess))]));
```suggestion
        if (!$this->URLsToProcess) {
            return md5(static::class);
        }
        return md5(implode('-', [static::class, implode('-', array_keys($this->URLsToProcess))]));
```
If there's nothing to process, then treating it as an array is improper - we should just have a signature that doesn't try to incorporate the URLs in that scenario.

2023-09-01 03:12 UTC, GuySartorelli commented
The only change I've made is resolving a linting issue

2023-09-01 03:13 UTC, GuySartorelli commented
@chrispenny You've been doing a lot of looking into this module recently and I'm not very familiar with it. This PR looks okay but can you please give it a quick glance and let me know if there's anything obviously problematic about this change?

2023-09-21 20:00 UTC, chrispenny commented
Sorry team, I've been away on annual leave.

The title of the PR makes it sound like we're going to make sure `URLsToProcess` is cast to an array, but instead it seems we're just checking that it is an array before attempting to loop over it. Either way sounds fine to me.

2023-09-21 21:37 UTC, GuySartorelli approved these changes
Looks good to me then. Thanks

2023-09-21 21:37 UTC, merged