MNT Delete StaticPublisherState
silverstripe/silverstripe-staticpublishqueue pull request #161
Opened 2023-02-15 23:20 UTC by emteknetnz

Issue https://github.com/silverstripeltd/product-issues/issues/676

When QueuedJobsTestService is used instead of QueueJobService in the context of recipe-kitchen-sink it's interfering with other unit tests that rely on the queuedjobs queue working

These classes were added in https://github.com/silverstripe/silverstripe-staticpublishqueue/pull/133 - though it seems as though it was added to work around an issue that queuedjobs module was having in CI at the time, rather than anything to do with staticpublishqueue

2023-02-15 23:26 UTC, GuySartorelli approved these changes, later dismissed
This fixes a bunch of problems we're experiencing in CI and seems to have only ever been introduced to work around an intermittent failure that was in queuedjobs in CI at the time.

Good change, just need @maxime-rainville 's approval

2023-02-15 23:47 UTC, maxime-rainville approved these changes, later dismissed
Approved post Beta API change.

Make sure you call it out on the RC changelog.

2023-02-16 00:10 UTC, emteknetnz commented
Have created PR for RC changleog - https://github.com/silverstripe/developer-docs/pull/161

2023-02-16 00:15 UTC, GuySartorelli requested changes

2023-02-16 00:15 UTC, GuySartorelli commented on README.md
> +# Unit-testing with StaticPublisherState to disable queuedjobs for unit-tests
```suggestion
## Unit-testing with StaticPublisherState to disable queuedjobs for unit-tests
```

2023-02-16 00:16 UTC, GuySartorelli approved these changes
Merge on green

2023-02-16 00:20 UTC, merged